// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htzcagxhnydzqdejpjps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0emNhZ3hobnlkenFkZWpwanBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTI3NDIsImV4cCI6MjA3Mzc2ODc0Mn0.ztkPawAod_Fwog8T9G2NgOc4Xq-HmDQiZOb-2wqUvL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});